pipeline {
    agent {
        docker {
           echo 'building docker' 
           
        }
    }
    
}
    stages {
        stage('Build') {
            steps {
                echo 'docker install'
            }
        }
        stage('Test') {
            steps {
                echo 'dockertest'
            }
        }
        
